version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: deps      
    command: yarn dev:server -- --host 0.0.0.0
    ports:
      - 3333:3333
    depends_on:
      - postgres
      - mongo
      - redis
    volumes:
      - ./backend/:/home/node/app/
      - /home/node/app/node_modules/

  frontend:
    build:
      context: ./frontend
      target: deps
    command: yarn start -- --host 0.0.0.0
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend/:/home/node/app/
      - /home/node/app/node_modules/

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=gobarber
    ports:
      - 5432:5432

  mongo:
    image: mongo
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
