name: Mobile Publish

on:
  push:
    branches: [ main ]
    paths:
    - 'mobile/**'
  workflow_dispatch:

jobs:
  publish:
    name: Install, test and publish a production version
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: mobile
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - uses: expo/expo-github-action@v6
      with:
        expo-version: 4.x
        expo-cache: true
        token: ${{ secrets.EXPO_TOKEN }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Publish a production version
      run: expo publish --release-channel=prod-v1